appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: WTitc8nOabT8w/DdxnNYkFIwJRA5zeYdFGme/nOod1Cr4G5hl2pe4rGx1r4BcSy8nUQB7McmA9ctoDqXnQgkgVKbY51rcpkLOFoFG4GFKFM8glWyIqKaYOPzXy9RlkI9yThAqb3Gu0JQEHweBmsCRmDlkSYliNfMTH0f1ovEKDnqI5QD2h4wyc0ndLQKeyVoEbNSaAVVUk8K5PZg8xBAPxIm6E/wG2LGKHnfpPGg2I5/ohZr+tXvOqid7S7OSBDaPAZggTbdnxPC/AmhQkmOVGZiaMh6OmDkAqihDwCDOBL+h0pgaTZav2x9cP5xEMEGvNeozhkkfmrUEUJQEvNzEbaLADgiFKM0mpLPn799DgvIsBym9+WQjShrkm9yHrVfFNloKtSfTqYr+3YjDzYFHiNqyZa24gYqnRH2LTB8OsOShR5Y83SPrvoFr9hx6BcKtpeGaxg5LjjSjb+Lj5emWcqtgwHU7+Qe+ecVNgb9dcmsu499HqlNCjTwhmZrZdr9w73iPTuz/TJUAOMy29H1qENs3c66Yg0+gfzpfx4OjllPVUO/iON2l4cl0aaDdrW35gFHOuejjykD6Ixh6yQWMHxOO4kFnW4wvIuUitOSAHUjl0ZEh7aWklG5KWUHA2ah5LJpxbvHJixC2i6iVHzb0gzCqXWwIDvBBUGrl6/SslI=}
